name: UI Automation
on:
  push:
    branches:
      - main

jobs:
  e2e-automation:
    name: E2E Selenium Automation
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Kill any leftover Chrome processes
        run: pkill chrome || true

      - name: Run Selenium tests
        run: |
          npm test
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: test-results/

      - name: Find Pull Request
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@v1
        with:
          branch: ${{ github.event.ref_name }}

      - name: Prepend artifact link to summary
        run: |
          echo "[⬇️ Download Selenium Test Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" | cat - test-results/test-results-summary.md > test-results/test-results-summary.with-link.md

      - name: Comment results on PR
        if: steps.find-pull-request.outputs.number != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.find-pull-request.outputs.number }}
          path: test-results/test-results-summary.with-link.md